

name: Deploy Dashboard (Static Website) to Sandbox Environment.

on:
 push:
  branches:
   - sandbox

env:
  BASE_URL: 'https://sandbox.coronavirus.data.gov.uk' 
  MAIN_CDN: 'sandbox.coronavirus.data.gov.uk' 
  DOWNLOADS_CDN: 'sandbox.coronavirus.data.gov.uk'  
  API_ENDPOINT: 'sandbox.coronavirus.data.gov.uk/api' 
  USER_API_ENDPOINT: 'api-sandbox.coronavirus.data.gov.uk' 
  APPINSIGHTS_INSTRUMENTATIONKEY: '0ab69a6e-1f5f-4c00-95a4-805490645471'  

jobs:
 deploy:
  runs-on: ubuntu-latest
  name: Deploy Dashboard (Static Website) to Sandbox Environment
  environment: sandbox

  steps:
  - name: Checks out the Repo
    uses: actions/checkout@v3

  - name: Installs and Setup Nodejs Version
    uses: actions/setup-node@v3
    with:
      node-version: '14.5.0'
  
  - name : Installs Dependancies 
    run: |
        npm install -g yarn
        npm install
        yarn install


  - name : Build Yarn
    run: |
        yarn run build

  - name: Azure Login
    uses: azure/login@v1
    with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}
      enable-AzPSSession: true

  - name: Deploy the files into $web container 
    uses: azure/CLI@v1
    with:
       azcliversion: 2.30.0
       inlineScript: |
          # Generate SAS token for the $web container
          $expiry=(Get-Date).AddMinutes(10).ToString("yyyy-MM-ddTHH:mm:ssZ")
          $sas=$(az storage container generate-sas --name "`$web" --account-name c19dashsbuksfe01static --permissions dlrw --expiry $expiry --auth-mode key -o tsv)
          # Upload files using the generated SAS token. We are using the sync command of azcopy which removes old files from storage
          azcopy sync "build" "https://c19dashsbuksfe01static.blob.core.windows.net/`$web?$sas" --delete-destination "true" --recursive --put-md5
          az logout









