

name: Deploy Dashboard (Static Website) to Sandbox Environment.

on:
 push:
  branches:
   - sandbox

jobs:
 deploy:
  runs-on: ubuntu-latest
  name: Deploy Dashboard (Static Website) to Sandbox Environment
  environment: sandbox

  steps:
  - name: Checks out the Repo
    uses: actions/checkout@v3

  - name: Installs and Setup Nodejs Version
    uses: actions/setup-node@v2.1.5
    with:
      node-version: '14'
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  
  - name : Installs Dependancies 
    run: |
        npm install --package-lock=false
        yarn install --production=true --no-lockfile


  - name : Build
    env:
        CI: false    
        BASE_URL: 'https://sandbox.coronavirus.data.gov.uk' 
        MAIN_CDN: 'sandbox.coronavirus.data.gov.uk' 
        DOWNLOADS_CDN: 'sandbox.coronavirus.data.gov.uk'  
        API_ENDPOINT: 'sandbox.coronavirus.data.gov.uk/api' 
        USER_API_ENDPOINT: 'api-sandbox.coronavirus.data.gov.uk' 
        APPINSIGHTS_INSTRUMENTATIONKEY: '0ab69a6e-1f5f-4c00-95a4-805490645471'
        BUILD_ENV: sandbox
        NODE_ENV: sandbox
    run: |
        npm run build
   
        
    ## Install the azcopy tool  
  - name: Install azcopy
    uses: kheiakiyama/install-azcopy-action@v1.0.3
    with:
        version: 'v10'
  - run: |
        azcopy_v10 sync "./build" "https://c19dashsbuksfe01static.blob.core.windows.net/$web?${{ secrets.STORAGE_SAS_KEY }}" --delete-destination "true" --recursive --put-md5











